sparkles: (feat) add optimization to all upsert and overwritepartitio…
Ferlab-Ste-Justine/unic-dag pull request #1043
Opened 2024-12-13 20:24 UTC by zoemcl

…ndynamic load types

2024-12-13 20:29 UTC, laurabegin requested changes

2024-12-13 20:29 UTC, laurabegin commented on dags/curated_quanumchartmaxx.py
> +CONFIG = "config/prod.conf"
Pourrait être mis dans lib/config?

2024-12-13 20:30 UTC, zoemcl commented on dags/curated_quanumchartmaxx.py
> +CONFIG = "config/prod.conf"
Ah finalement il l'est déjà. Je vais l'utiliser

2024-12-13 20:55 UTC, 0xjaafar approved these changes

2024-12-16 15:43 UTC, laurabegin requested changes

2024-12-16 15:43 UTC, laurabegin commented on dags/curated_philips.py
> +                                  , "phillips", ZONE, "curated", config_file, jar, dag)
Virgule en début de ligne

2024-12-16 15:47 UTC, zoemcl commented on dags/curated_philips.py
> +                                  , "phillips", ZONE, "curated", config_file, jar, dag)
done

2024-12-16 15:48 UTC, laurabegin approved these changes

2024-12-16 15:50 UTC, merged