Added new indicateurs dataset_ids
Ferlab-Ste-Justine/unic-dag pull request #134
Opened 2022-11-18 20:12 UTC by dtremblay-sher

2022-11-18 22:01 UTC, laurabegin requested changes

2022-11-18 22:01 UTC, laurabegin commented on dags/config/ingestion/pharmacie_config.json
> +        {"dataset_id":"anonymized_pharmacie_g*"                              , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": []},
Hmm normalement c'est déjà comme ça sur master. Il devrait juste y avoir les changements dans indicateurs_config. Essaie de refaire ton rebase 🤔

2022-11-21 14:08 UTC, dtremblay-sher commented on dags/config/ingestion/pharmacie_config.json
> +        {"dataset_id":"anonymized_pharmacie_g*"                              , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": []},
hmmm j'ai refait le rebase je sais pas si ca a marche cette fois

2022-11-21 14:12 UTC, laurabegin commented on dags/config/ingestion/pharmacie_config.json
> +        {"dataset_id":"anonymized_pharmacie_g*"                              , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": []},
C'est bon 🙂

2022-11-21 14:12 UTC, laurabegin approved these changes

2022-11-21 17:12 UTC, merged