:safety_vest: update schedule_interval to reflect changes from Martin
Ferlab-Ste-Justine/unic-dag pull request #239
Opened 2023-03-22 15:03 UTC by pycodemaker

# Description

This PR updates the schedule_interval of the DAG based on the information in a new Excel from Martin. However, please note the following:
- I ve not performed any timezone translation when updating the `schedule_interval` 
- My logic while reading the excel sheet

I would appreciate it if could pay extra attention to the following areas:
when schemas has multiple elements like:`"schemas": ["softlab", "softmic"],` from excel sheet provided by Martin last element were: `V_P_LAB_TEST_RESULT` tuesday at 22h so I updated the cron expression as the following: `0 23 * * 2` 

Thanks a lot !

2023-03-22 15:39 UTC, laurabegin commented
Les expressions cron doivent être en UTC. Donc il faut faire de la conversion.

2023-03-22 16:22 UTC, pycodemaker commented
> oivent être en UTC. Donc il faut faire

2023-03-22 16:46 UTC, laurabegin requested changes
Tu peux faire +1 à toutes les cédules car l'horaire est en EST (-5:00). Désolée j'aurais dû te le dire...

2023-03-23 14:48 UTC, laurabegin requested changes

2023-03-23 14:48 UTC, laurabegin commented on dags/config/ingestion/clinibaseci_config.json
> +  "schedule": "0 9 * * 3",
"0 12 * * 3"

2023-03-23 14:48 UTC, laurabegin commented on dags/config/ingestion/eclinibase_reference_config.json
> +  "schedule": "0 6 * * 3",
"0 5 * * 3"

2023-03-23 14:48 UTC, laurabegin commented on dags/config/ingestion/etraceline_config.json
> +  "schedule": "0 5 * * 6",
"0 9 * * 6"

2023-03-23 14:48 UTC, laurabegin commented on dags/config/ingestion/opera_config.json
> +  "schedule": "0 12 * * 6",
"0 13 * * 6"

2023-03-23 14:48 UTC, laurabegin commented on dags/config/ingestion/staturgence_config.json
> +  "schedule": "0 23 * * 4",
"0 3 * * 5" (3h am le vendredi)

2023-03-23 15:30 UTC, pycodemaker commented
Gros merci j'étais pas sur de bien comprendre mais avec tes commentaires ca m'a bcp aider ! merci Laura

2023-03-23 15:34 UTC, laurabegin approved these changes

2023-03-23 15:44 UTC, merged