UNIC-1124: anonymized growthxp
Ferlab-Ste-Justine/unic-dag pull request #319
Opened 2023-07-27 21:11 UTC by zoemcl

2023-07-28 12:43 UTC, laurabegin requested changes

2023-07-28 12:43 UTC, laurabegin commented on dags/config/ingestion/growthxp_config.json
>        {"dataset_id":"raw_growthxp_visit"  , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": []}
Est-ce qu'on peut supprimer le fichier au complet vu que le raw n'est plus utile?

2023-07-28 12:43 UTC, laurabegin commented on dags/config/anonymized/growthxp_config.json
> +  "schedule": null,
Est-ce que Martin va suivre la même cédule avec Talend?

2023-07-28 15:31 UTC, zoemcl commented on dags/config/ingestion/growthxp_config.json
>        {"dataset_id":"raw_growthxp_visit"  , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": []}
Je le garde pour la cédule qui roule ajourd'hui, en faite je viens de remmentre le step anonymized dans le fichier conf d'ingestion. Martin va pas faire la transition avant la semaine prochaine. Je le sépare pour tester.

2023-07-28 15:32 UTC, zoemcl commented on dags/config/anonymized/growthxp_config.json
> +  "schedule": null,
Oui je pense. Une fois que je complète le test je vais lui dire de céduler growthxp

2023-07-31 13:34 UTC, laurabegin approved these changes

2023-07-31 13:39 UTC, merged