UNIC-1170: modification du start_date et remplacer ds par data_interv…
Ferlab-Ste-Justine/unic-dag pull request #341
Opened 2023-08-03 15:28 UTC by sallyalomar

…al_end | ds dans ingestion_philips, ajout de DOC

2023-08-04 15:44 UTC, laurabegin requested changes

2023-08-04 15:44 UTC, laurabegin commented on dags/ingestion_cathydb.py
> +Cet ETL roule pour ingérer les données à haute résolution neonat et SIP à partir de CathyDB depuis le 21 Janvier 2017.
Le start date indique plutôt 2016-12-2.

2023-08-04 15:44 UTC, laurabegin commented on dags/ingestion_philips.py
> +* __Date de début__ - 23 Janvier 2023
C'est le 29 le start date

2023-08-07 12:33 UTC, laurabegin requested changes

2023-08-07 12:33 UTC, laurabegin commented on dags/ingestion_cathydb.py
> +"""
Rajouter que pour les données de neonat, c'est seulement l'historique et qu'à partir du 29 mars 2023, les données sont ingérées avec le dag philips.

2023-08-07 12:33 UTC, laurabegin commented on dags/ingestion_philips.py
> +
Pas besoin de parler du fix de performance

2023-08-07 12:33 UTC, laurabegin commented on dags/ingestion_cathydb.py
> +La date de l'ingestion correspond à la date d'enregistrement de la données dans la BDD Cathydb.
Expliquer que la date de la run dans Airflow ingère les données de cette journée : ex la run du 1 janvier 2020 ingère les données du 1 janvier 2020 dans le lac.

2023-08-07 12:33 UTC, laurabegin commented on dags/ingestion_philips.py
> +Cet ETL roule quotidiennement à 3h le matin pour ingérer les données neonat enregistrées le jour précédent à partir de la BDD Philips.PatientData.
Expliquer que la date de la run dans Airflow ingère les données de la journée précédente journée : ex la run du 1 janvier 2020 ingère les données du 31 décembre 2019 dans le lac.

2023-08-09 00:57 UTC, sallyalomar commented on dags/ingestion_cathydb.py
> +ETL d'ingestion des données à haute résolution neonat et SIP à partir de CathyDB
oui ! mais je suggère que ça soit une heure différente puisque ce sont les données haute résolution sauf si avec le fix de performance ça sera ok.... mais je pense qu'on peut laisser comme ça pour le moment avant le faire ce changement puisqu'on a des années à ingérer avant qu'on commence l'ingestion quotidienne... qu'en penses-tu ?

2023-08-09 18:16 UTC, merged