UNIC-1067: adding date as arg hl7 DAGs
Ferlab-Ste-Justine/unic-dag pull request #363
Opened 2023-08-22 01:01 UTC by zoemcl

2023-08-22 13:34 UTC, laurabegin requested changes
+ fix le pipeline

2023-08-22 13:34 UTC, laurabegin commented on dags/curated_radimage_hl7.py
> +    catchup=True,
Il faudrait une start_date pour savoir à partir de quelle date il doit commencer le catchup.

2023-08-22 13:34 UTC, laurabegin commented on dags/curated_radimage_hl7.py
> +        arguments=["config/prod.conf", "initial", "curated_radimage_hl7_oru_r01", '{{ds}}'],  # {{ds}} input date
Initial pour tester j'imagine?

2023-08-22 14:52 UTC, zoemcl commented on dags/curated_radimage_hl7.py
> +        arguments=["config/prod.conf", "initial", "curated_radimage_hl7_oru_r01", '{{ds}}'],  # {{ds}} input date
yes pour tester!

2023-08-23 14:24 UTC, laurabegin requested changes

2023-08-23 14:24 UTC, laurabegin commented on dags/curated_radimage_hl7.py
> +    default_args=default_args.update({
update met à jour le default_args sans le retourner, donc c'est comme si tu passais null à default args. Faut le faire en 2 temps (voir autres DAGs). Le start_date peut aussi être mis au niveau du dag.

2023-08-23 17:17 UTC, laurabegin approved these changes

2023-08-23 17:27 UTC, merged