Added dag things for choriobact.  set everything to initial for the f…
Ferlab-Ste-Justine/unic-dag pull request #382
Opened 2023-09-12 12:22 UTC by dtremblay-sher

…irst run?

2023-09-12 13:34 UTC, laurabegin requested changes

2023-09-12 13:34 UTC, laurabegin commented on dags/config/enriched/choriobact_config.json
> +        {"dataset_id":"enriched_choriobact_mother_blood_culture"                , "cluster_type": "small", "run_type": "initial", "cluster_specs": {}, "dependencies": []},
Les dataset_ids devraient référer à released. Les run_type devraient être en default.

2023-09-13 15:48 UTC, dtremblay-sher commented on dags/config/enriched/choriobact_config.json
> +        {"dataset_id":"enriched_choriobact_mother_blood_culture"                , "cluster_type": "small", "run_type": "initial", "cluster_specs": {}, "dependencies": []},
ok fixed!

2023-09-13 15:49 UTC, laurabegin approved these changes

2023-09-14 13:43 UTC, merged