:rocket: feat: add tasks to handle numeric_data tables & little refactor
Ferlab-Ste-Justine/unic-dag pull request #487
Opened 2023-12-11 20:07 UTC by 0xjaafar

2023-12-11 20:11 UTC, 0xjaafar commented
Pour le test qui faille je rajoute la doc pour la fonction j'étais pas au courant que c'est obligaoire

2023-12-13 18:11 UTC, laurabegin requested changes

2023-12-13 18:11 UTC, laurabegin commented on dags/curated_philips.py
> +        arguments=arguments,
Les arguments doivent nommés, voir dag ingestion_cathydb

2023-12-13 19:28 UTC, 0xjaafar commented on dags/curated_philips.py
> +        arguments=arguments,
good catch j'ai oublié que ca été mis à jour, j'ai changé pour utiliser le named arg

2023-12-13 20:23 UTC, laurabegin approved these changes

2023-12-13 20:24 UTC, merged