Unic 1022
Ferlab-Ste-Justine/unic-dag pull request #699
Opened 2024-05-02 13:09 UTC by zoemcl

2024-05-02 14:10 UTC, 0xjaafar commented on dags/spark_operators.py
> +            pre_test_jobs
ca fait quoi cette ligne?

2024-05-02 14:11 UTC, 0xjaafar commented on dags/spark_operators.py
> +            post_test_jobs
même chose ici pas sur de comprendre

2024-05-02 14:18 UTC, 0xjaafar commented on dags/spark_operators.py
> +                   datasets: list):
le typehint est optionnel mais comme tu l'as utilisé dans les params peut-être rajouter le return type aussi -- commentaire optionnel
`-> TaskGoup:`

2024-05-02 14:21 UTC, 0xjaafar commented on dags/spark_operators.py
> +                all_pre_tests = all_pre_tests + conf['pre_tests']
tu peux utiliser `all_pre_tests.extend `si tu veux

2024-05-02 14:23 UTC, 0xjaafar commented on dags/spark_operators.py
> +                        job['job']
première fois que je vois des expressions comme ça `job['job'] ` qu'est ce que cava faire ?

2024-05-02 18:05 UTC, laurabegin requested changes

2024-05-02 18:05 UTC, laurabegin commented on dags/spark_operators.py
> +        with TaskGroup(group_id="pre_tests") as pre_test_sub_group:
Utiliser le TaskFlow API

2024-05-02 18:05 UTC, laurabegin commented on dags/spark_operators.py
> +        with TaskGroup(group_id="pre_tests") as pre_test_sub_group:
On pourrait s'inspirer de ce que j'ai fait dans clin. J'ai défini des groupes et des tasks : 
https://github.com/Ferlab-Ste-Justine/clin-pipelines-dags/tree/master/dags/lib/groups 
https://github.com/Ferlab-Ste-Justine/clin-pipelines-dags/tree/master/dags/lib/tasks

2024-05-03 16:07 UTC, zoemcl commented on dags/spark_operators.py
> +        with TaskGroup(group_id="pre_tests") as pre_test_sub_group:
Alors l'idée c'est e crée un API qui retourne des Task au lieu d'utiliser create_spark_job() et create_spark_test()?

2024-05-06 16:16 UTC, laurabegin approved these changes

2024-05-06 16:23 UTC, merged