:sparkles: (feat) optimize delta tables dag
Ferlab-Ste-Justine/unic-dag pull request #863
Opened 2024-09-05 19:59 UTC by zoemcl

2024-09-05 20:15 UTC, zoemcl commented on dags/optimize_delta_tables.py
> +            number_of_versions,
ouais ca serait cool. Pour l'ETL avec optimiaation, on pourra filtrer sur une partition, la derniere. Mais je pense que ca serait cool de l'avoir comme option ici aussi.

2024-09-05 20:20 UTC, zoemcl commented on dags/optimize_delta_tables.py
> +        return int("{{ params.number-of-versions or '' }}") # this may fail, try dagRun if case
nop je vais les enlever!

2024-09-05 20:21 UTC, laurabegin commented on dags/optimize_delta_tables.py
> +            number_of_versions,
Ah ouais! Ça pourrait être un flag. Exemple si tu mets last partition only ça va faire le datasetconf, ça check partitionBy, ça prend la valeur la plus grande et ça roule le compact juste dessus.

2024-09-06 19:26 UTC, laurabegin requested changes

2024-09-06 19:26 UTC, laurabegin commented on dags/optimize_delta_tables.py
> +    def get_dataset_ids(ti=None) -> List[str]:
Pas une task. Manque le header

2024-09-06 19:40 UTC, zoemcl commented on dags/optimize_delta_tables.py
> +    def get_dataset_ids(ti=None) -> List[str]:
est ce que il doit etre rouler avant dans ce cas ou on peux l'appeler directement?

2024-09-06 19:41 UTC, laurabegin commented on dags/optimize_delta_tables.py
> +    def get_dataset_ids(ti=None) -> List[str]:
Normalement en le callant ça le roule. Mais moi je le mets aussi dans le graphe de dépendances pour faire un DAG clean. Comme j'ai fait dans les DAGs de catalogue.

2024-09-09 15:42 UTC, zoemcl commented on dags/optimize_delta_tables.py
> +    def get_dataset_ids(ti=None) -> List[str]:
Jai aussi update get_number_of_versions

2024-09-09 17:06 UTC, laurabegin requested changes

2024-09-09 17:06 UTC, laurabegin commented on dags/optimize_delta_tables.py
> +    def get_number_of_versions(ti=None) -> int:
Tu peux faire comme get_zone(). Pas besoin de mettre dans une task.

2024-09-09 17:06 UTC, laurabegin commented on dags/optimize_delta_tables.py
> +    @task
Ne pas mettre task vu que ça retourne un SparkOperator. @task c'est pour faire un PythonOperator.

2024-09-09 18:44 UTC, laurabegin approved these changes

2024-09-09 18:51 UTC, merged