:recycle: chore(eclinibase): refactor eclinibase dag and add new tables focus on regex
Ferlab-Ste-Justine/unic-dag pull request #970
Opened 2024-11-19 21:12 UTC by 0xjaafar

2024-11-19 21:19 UTC, laurabegin commented on dags/config/yellow/anonymized/eclinibase_config.json
> +      {"dataset_id": "anonymized_eclinibase_v_unite_statistique"      , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": [], "pre_tests": [], "post_tests": []}
Est-ce qu'on devrait rajouter des QA tests?

2024-11-20 14:59 UTC, 0xjaafar commented on dags/config/yellow/anonymized/eclinibase_config.json
> +      {"dataset_id": "anonymized_eclinibase_v_unite_statistique"      , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": [], "pre_tests": [], "post_tests": []}
Done

2024-11-20 15:03 UTC, zoemcl requested changes

2024-11-20 15:03 UTC, zoemcl commented on dags/config/yellow/anonymized/eclinibase_config.json
> +      {"dataset_id": "anonymized_eclinibase_v_unite_statistique"      , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": [], "pre_tests": ["greater_partition_coun
Je pense qu'on devrait mettre '"lower_or_equal_null_counts" dans les post test?

2024-11-20 15:03 UTC, zoemcl commented on dags/config/yellow/anonymized/eclinibase_config.json
> +      {"dataset_id": "anonymized_eclinibase_v_unite_statistique"      , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": [], "pre_tests": ["greater_partition_coun
comme il a des transformations sur les dates

2024-11-20 15:06 UTC, 0xjaafar commented on dags/config/yellow/anonymized/eclinibase_config.json
> +      {"dataset_id": "anonymized_eclinibase_v_unite_statistique"      , "cluster_type": "small" , "run_type": "default", "cluster_specs": {}, "dependencies": [], "pre_tests": ["greater_partition_coun
done

2024-11-20 15:07 UTC, zoemcl approved these changes

2024-11-20 15:07 UTC, merged